colors:
  light:
    classes: "#baa7e5"
    abstract_classes: "#a7e5a7"
    interfaces: "#e2c7a3"
    modules: "#5ab3f4"
  dark:
    classes: "#2e1065"
    abstract_classes: "#365314"
    interfaces: "#af6300"
    modules: "#0041cc"

paths:
  - src/entities
  - examples/

namespaces:
  E2:
    - E2::Organization
    - E2::Enterprise
    - E2::Bank
  E3:
    - E3::Universe
    - E3::Galaxy
    - E3::BlackHole
    - E3::Planet
    - E3::Star
  E11:
    - E11::G1::Link
    - E11::G2::Sublink
    - E11::G3::SubSublink
    - E11::G3::AnotherSubSublink