site_name: Cruml Documentation
theme:
  name: material
  palette:
    primary: deep-purple
  icon:
    repo: material/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

repo_url: https://github.com/tamdaz/cruml
repo_name: tamdaz/cruml