site_name: Cruml Documentation
theme:
  name: material
  palette:
    primary: deep-purple
  icon:
    repo: material/github
  features:
    - search.share
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - Home:
    - index.md
  - Get started:
    - Installation: get_started/1_installation.md
    - Generate a class diagram: get_started/2_generate_a_class_diagram.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

repo_url: https://github.com/tamdaz/cruml
repo_name: tamdaz/cruml